<html>
    <head>
        <title>Error handling</title>
    </head>
    <body>
        <script>
            class ValidationError extends Error {
                constructor(message, field){
                    super(message);
                    this.field = field
                }
            }

            // Throw Error
            class MathUtil {
                static sum(...numbers) {
                    if (numbers.length === 0){
                        throw new ValidationError("Total parameter harus lebih dari 0", "numbers")
                    }

                    let total = 0
                    for (const number of numbers) {
                        total += number;
                    }
                    return total;
                }

            }
            
            
            const sum = MathUtil.sum(1, 2, 3);
            console.log(sum)
                        
            // Error Handling (Jika error ini tidak akan memberhentikan kode dibawahnya try&catch)
            try {
                console.info(MathUtil.sum());
                console.info("Kode Block Try akan berhenti")
            } catch (error) {
                if(error instanceof ValidationError){
                    console.info(`Terjadi Error di field ${error.field} dengan error ${error.message}`)
                }
            } finally {
                console.info("Program End") // mau error atau tidak tetap akan di eksekusi
            }

            console.info("Masih Lanjut")

            console.log(MathUtil.sum());

            console.log("tidak di lanjut") // Tidak muncul di console

            </script>
    </body>
</html>